// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6io-ddg3VMeSg3sFl6XZoqo-A-eEqlgo',
    appId: '1:111695129746:web:a24e0f7b1158faea3e0a4b',
    messagingSenderId: '111695129746',
    projectId: 'flutter-camera-challenge',
    authDomain: 'flutter-camera-challenge.firebaseapp.com',
    storageBucket: 'flutter-camera-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZJ955ml85FcQVaAfSU_utvemlG-tsyU',
    appId: '1:111695129746:android:641b3b1bf7f5e46a3e0a4b',
    messagingSenderId: '111695129746',
    projectId: 'flutter-camera-challenge',
    storageBucket: 'flutter-camera-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7SNSmOYBjR8aSTyxFIvJ6sVDopZo0bPw',
    appId: '1:111695129746:ios:5e74efff2e0355783e0a4b',
    messagingSenderId: '111695129746',
    projectId: 'flutter-camera-challenge',
    storageBucket: 'flutter-camera-challenge.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCameraChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7SNSmOYBjR8aSTyxFIvJ6sVDopZo0bPw',
    appId: '1:111695129746:ios:d7b325deda6a095f3e0a4b',
    messagingSenderId: '111695129746',
    projectId: 'flutter-camera-challenge',
    storageBucket: 'flutter-camera-challenge.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCameraChallenge.RunnerTests',
  );
}
